### ISSUE TITLE
It scrolls up when you make a table

### ISSUE THREAD

**Issue by hyperphysin** [davisriedel/obsidian-typewriter-mode#85] opened 2024-10-08 23:09 UTC
![Oct-09-2024 08-07-28](https://github.com/user-attachments/assets/0c3cfccc-727f-4535-9a60-c672bdaa83a2)

**Comment by davisriedel** [comment] 2024-10-13 18:12
Duplicate of #61

**Closed by davisriedel** 2024-10-13 18:12 UTC
