### ISSUE TITLE
Blurred text in .canvas files

### ISSUE THREAD

**Issue by IndyGibb** [davisriedel/obsidian-typewriter-mode#37] opened 2023-10-23 20:14 UTC
I recently got this plugin because I like the look of it, but now when I type in a card in a canvas file, it blurs the text. Below is a picture of what it looks like.
![image](https://github.com/davisriedel/obsidian-typewriter-mode/assets/148816223/191c83a4-2238-4a07-be38-bf2733c8d55a)
I want to use this plugin, but having to turn it off every time I'm editing a canvas will get a little annoying. Is there a fix?

**Comment by davisriedel** [comment] 2023-11-01 11:59
I do not get the blurring on my machine. Which obsidian version are you using and on which operating system are you? Does the blurring only appear if Typewriter Mode is enabled? Or only if a specific setting of Typewriter Mode is enabled?

**Comment by davisriedel** [comment] 2024-01-24 22:59
Because I could not reproduce this, and with the newest beta `0.0.6-beta.2` you can disable the plugin in canvas, I am closing this issue for now. Feel free to reopen it, if you still have problems.

**Closed by davisriedel** 2024-01-24 22:59 UTC
Labels: bug
