### ISSUE TITLE
Typewriter offset not working

### ISSUE THREAD

**Issue by Drakemoor** [davisriedel/obsidian-typewriter-mode#51] opened 2024-02-05 20:24 UTC
Anything above Typewriter offset > 55 is not working. 

If I put any value bigger than that, it just stops doing anything.

There are no errors in the console.

**Comment by davisriedel** [comment] 2024-06-22 17:05
I could not reproduce this in my test vault. Do you have any other plugins that interfere with scrolling? Maybe it only occurs when the window has a certain size or the display has a certain resolution. Please provide a few more details.

**Comment by davisriedel** [comment] 2024-08-01 09:22
I am closing this issue for now. Please reach out, if the issue persists and provide the requested details.

**Closed by davisriedel** 2024-08-01 09:22 UTC
Labels: bug
